-- EDA Project

-- Dimension vs Measures

-- If data type of a column is not numeric (e.g. String or Date)
-- then it is a DIMENSION

-- If data type of a column is numeric 
-- Then we ask another question: Does it make sense to aggregate it?
-- For example, phone numbers are numeric but it doesn't make sense to find 
-- the average of phone numbers

-- If it makes sense to aggregate, then the column is a MEASURE
-- Otherwise it is a DIMENSION

-- Dimensions are used for grouping up data (GROUP BY)
-- Measures are used for aggregating data 


-- Explore all objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'


-- Dimensions Exploration
-- Identifying the unique values (categories) in each dimension
-- Helps recognise how data might be grouped or segmented


-- Explore all the countries our customer come from
SELECT DISTINCT Country FROM gold.dim_customers

-- Explore all categories "The major divisions"
SELECT DISTINCT Category, subcategory, product_name 
FROM gold.dim_products
ORDER BY 1,2,3

-- Date Exploration
-- Identify the earliest and latest dates (boundaries)
-- Understand the scope of data and the timespan

-- Finding the earliest and latest dates
SELECT 
MIN(order_date) first_order_date, 
MAX(order_date) last_order_date,
DATEDIFF(year, MIN(order_date), MAX(order_date)) order_range_years
FROM gold.fact_sales

-- Finding the youngest and oldest customers
SELECT 
MIN(birthdate) oldest_birthdate, 
MAX(birthdate) youngest_birthdate,
DATEDIFF(year, MIN(birthdate), GETDATE()) oldest_age,
DATEDIFF(year, MAX(birthdate), GETDATE()) youngest_age
FROM gold.dim_customers


-- Measures Exploration
-- Calculate the key metrics of our business (the big numbers)
-- Highest level of aggregation, lowest level of details

-- Find the total sales
SELECT SUM(sales_amount) TotalSales FROM gold.fact_sales 

-- Find how many items are sold
SELECT SUM(quantity) TotalProductsSold FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) AvgSellingPrice FROM gold.fact_sales 

-- Find the total number of orders
SELECT COUNT(order_number) TotalOrders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) TotalOrders FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(product_id) TotalProducts FROM gold.dim_products

-- Find the total number of customers
SELECT COUNT(customer_id) TotalCustomers FROM gold.dim_customers

-- Find the total number of customers that have placed an order
SELECT COUNT(DISTINCT customer_key) TotalCustomersOrderPlaced FROM gold.dim_customers dc 
WHERE EXISTS(SELECT 1 FROM gold.fact_sales fs WHERE dc.customer_key = fs.customer_key)

SELECT COUNT(DISTINCT customer_key) TotalCustomersOrderPlaced FROM gold.fact_sales

-- Combined report

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales 
UNION ALL
SELECT 'TotalProductsSold' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales 
UNION ALL
SELECT 'AvgSellingPrice' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales 
UNION ALL
SELECT 'TotalOrders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales 
UNION ALL
SELECT 'TotalProducts' AS measure_name, COUNT(product_id) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'TotalCustomers' AS measure_name, COUNT(customer_id) AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'TotalCustomersOrderPlaced' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold.dim_customers


-- Magnitude Analysis
-- Comparing the measure values by categories
-- [Measure] By [Dimension]
-- e.g. Total Sales by Country
-- Total Quantity by Category

-- Total Customers by countries

SELECT country, COUNT(customer_key) TotalCustomers 
FROM gold.dim_customers
GROUP BY country
ORDER BY TotalCustomers DESC

-- Total Customers by gender

SELECT gender, COUNT(customer_key) TotalCustomers 
FROM gold.dim_customers
GROUP BY gender
ORDER BY TotalCustomers DESC

-- Total Products by category

SELECT category, COUNT(product_key) TotalProducts 
FROM gold.dim_products
GROUP BY category
ORDER BY TotalProducts DESC

-- Average Costs of Products in each category

SELECT category, AVG(cost) AvgCost
FROM gold.dim_products
GROUP BY category


-- Total Revenue generated for each category


SELECT dp.category, SUM(fs.TotalSales) TotalRevenue FROM gold.dim_products dp 
JOIN 
(SELECT product_key, SUM(sales_amount) TotalSales FROM gold.fact_sales
GROUP BY product_key) fs 
ON dp.product_key = fs.product_key
GROUP BY category

-- Total Revenue generated by each customer

SELECT dc.customer_key, dc.first_name, dc.last_name, fs.TotalSales 
FROM gold.dim_customers dc
JOIN
(SELECT customer_key, SUM(sales_amount) TotalSales FROM gold.fact_sales
GROUP BY customer_key) fs
ON dc.customer_key = fs.customer_key

-- Distribution of Sold items across Countries

SELECT dc.country, SUM(fs.TotalItems) TotalItemsSold
FROM gold.dim_customers dc
JOIN
(SELECT customer_key, SUM(quantity) TotalItems FROM gold.fact_sales
GROUP BY customer_key) fs
ON dc.customer_key = fs.customer_key
GROUP BY country


-- Ranking
-- Ranking a Dimension by a Measure
-- e.g. Ranking Countries by Total Sales
-- Top 5 Products by Quantity

-- 5 Products that generate the highest revenue

SELECT TOP 5 p.product_key, p.product_name, SUM(sales_amount) TotalRevenue FROM gold.fact_sales f
JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_key, p.product_name
ORDER BY TotalRevenue DESC


-- Using Window Function
SELECT * FROM
(
    SELECT
    p.product_name, 
    SUM(sales_amount) TotalRevenue,
    ROW_NUMBER() OVER(ORDER BY SUM(sales_amount) DESC) Rank 
    FROM gold.fact_sales f
    JOIN gold.dim_products p
    ON f.product_key = p.product_key
    GROUP BY p.product_name
)t WHERE Rank <= 5



-- 5 worst-performing products in terms of sales

SELECT TOP 5 p.product_key, p.product_name, SUM(sales_amount) TotalRevenue FROM gold.fact_sales f
JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_key, p.product_name
ORDER BY TotalRevenue ASC


-- Using Window Function
SELECT * FROM
(
    SELECT
    p.product_name, 
    SUM(sales_amount) TotalRevenue,
    ROW_NUMBER() OVER(ORDER BY SUM(sales_amount) ASC) Rank 
    FROM gold.fact_sales f
    JOIN gold.dim_products p
    ON f.product_key = p.product_key
    GROUP BY p.product_name
)t WHERE Rank <= 5

-- Top 10 Customers who have generated the highest revenue

SELECT TOP 10 c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount) TotalRevenue FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY TotalRevenue DESC

-- 3 Customers with fewest orders placed

SELECT TOP 3 c.customer_key, c.first_name, c.last_name, COUNT(DISTINCT f.order_number) TotalOrders FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY TotalOrders ASC